### PR TITLE
Improved support for ADW Launcher 2.0.

### PR DESCRIPTION
**Pull request by AnderWeb**
This adds the ADW icons and xml config to support ADW Launcher.

This also adds a feature to return icon resources instead a Bitmap from the icon picker.
Most launchers use their own internal picker for icon packs, but others prefer that each icon pack can create its own UI (or use dashboards like Polar). 
In those cases, the launcher can support to receive the Intent.ShortcutIconResource to store the drawable reference instead the whole Bitmap so, if the Icon Pack is uninstalled, the icon can no longer be used.

### CODE REVIEW

**Comment by afollestad** [comment]
Thank you!

**Comment by TWellington** [comment]
Thanks @AnderWeb! We appreciate your contributions

**Comment by Technologx** [comment]
Thanks man this will come in handy you know since ADW finally decided to update their launcher

**Comment by afollestad** [comment]
@Technologx this PR was made by the developer of ADW 😛

**Comment by Technologx** [comment]
Ahh well I like that they finally updated sorry I got a bit confused

**Pull request merged**
